### ISSUE TITLE
General meeting: 進行分組與分配任務

### ISSUE THREAD

**Issue by aa89227** [Game-as-a-Service/Monopoly#35]
# 時間
2023年4月30日 星期日 下午一點
約兩小時

# 議程

1. 討論進度
 #33
 #34
 
2. 討論這次要進行的feature是哪些
3. 進行分組
4. 1~2人一組，各組會進行為期兩週的合作開發
5. 分配各組的Issue

# 其他事項
在這次的會議後，若有人想要的話，就找一個feature進行ATDD

**Comment by Bean90638** [comment]
1. 任務進度
  1. #33 :已成功，但需要重構
  2. #34 :改成下周任務
2. Alpha問題
    1. 進度: 前端:0% 後端:(用ATDD項目來看的話是20%) 不確定之前aa回報多少
    2. 人數: 前端:同後端 後端:4人(aa、Melo、Brad、Rick)
    3. 設計師: 需要，但可能要等進度到達前端時候
3. 其他
    1. @RobbinHsu啟動問題: 沒想到解法
